/* Runs the REAL Supabase edge function under real Deno against stubs of every service it calls.

   Why this file exists. tests/edge-function.js exercises the Cloudflare Pages variant, and the
   Supabase module — the one that actually serves the site — had no runner at all. `node --check`
   cannot parse .ts, and Deno's type checker only reports the file's pre-existing looseness, so a
   route that was unreachable at runtime (the lock's 404 swallowing /fulfill) survived every check
   I had, and an integer overflow that zeroed the payment watermark survived everything else. This
   imports the deployed module and calls its handler, so routing, ordering, RPC shapes and the chain
   matcher all really execute.

   Two ordering rules this file exists to obey:
     · the stub must be LISTENING before the module is imported (the module reads PROJECT_URL at top
       level), and its URL knobs must be set before the import too — setting them afterwards leaves
       the test quietly hitting the real Coinbase and passing on live data;
     · the assertions must not depend on the internet. The 'nothing escaped to the real internet'
       check enforces that, because a suite that passes by making real calls is not reproducible.

   The stub's crypto_quote re-implements the amount-reservation rule ON PURPOSE so the retry path is
   asserted rather than assumed — which means this file tests the function against a MODEL of the
   database, while tools/verify-crypto.js tests it against the database itself. Both, deliberately:
   one catches logic, the other catches SQL.

     Run: node tests/edge-deno.js         (or: deno run --allow-all tests/edge-deno.js)
     Deno: $DENO_BIN, ~/.deno/bin/deno, /tmp/denobin/deno, then PATH. Missing runtime = SKIP, not
     failure: a runtime I could not install is not a bug in your site.                        */
'use strict';

const path = require('path');
const fs = require('fs');
const os = require('os');
const { spawnSync } = require('child_process');

const ROOT = path.join(__dirname, '..');
const SRC = path.join(ROOT, 'supabase/functions/annotate/index.ts');

const DENO = (() => {
  const cands = [process.env.DENO_BIN, path.join(os.homedir(), '.deno/bin/deno'), '/tmp/denobin/deno'].filter(Boolean);
  for (const c of cands) if (fs.existsSync(c)) return c;
  const w = spawnSync('deno', ['--version'], { encoding: 'utf8' });
  return w.status === 0 ? 'deno' : '';
})();

if (!DENO) {
  console.log('\n\u2713 edge-deno: SKIP \u2014 no deno runtime found (set DENO_BIN or install deno)');
  process.exit(0);
}

/* The harness body is a Deno program, kept as a raw string so its own escapes survive verbatim.
   Note it uses no outer-template interpolation at all: `${` inside String.raw would still be
   evaluated, and a stray backtick in a comment would truncate the file in a way that reads as a
   syntax error hundreds of lines away. */
const HARNESS = String.raw`/* generated by tests/edge-deno.js - edit the Node file, not this one */
const store = {
  cfg: {}, cache: {}, refs: [], txs: {}, quotes: new Map(), mintDays: null,
  mintLabels: [], calls: [], errors: [], tip: 100, refsError: 0,
  rateBodies: {
    coinbase: { data: { amount: '50' } },
    kraken: { result: { XLTCZUSD: { c: ['51', '1', '1'] } } },
    fx: { rates: { NGN: 1500 } }
  }
};

const rpcHandler = async (req) => {
  const u = new URL(req.url);
  // PostgREST puts a function's return value DIRECTLY in the body: an object/JSONB as the object, a
  // scalar TEXT as a bare JSON string, RETURNS VOID as no body at all. The harness used to wrap all
  // three as {value: …} — a shape that never occurs on the wire — and the module grew code to match
  // the lie, which is precisely how every app_config read broke in production while staying green here.
  const send = (code, obj) => new Response(obj === undefined ? null : JSON.stringify(obj),
    { status: code, headers: { 'content-type': 'application/json' } });
  const fn = u.pathname.split('/').pop();
  const a = await req.json().catch(() => ({}));
  store.calls.push({ fn, a });
  if (fn === 'cfg') return send(200, store.cfg[a.p_key] ?? null);   // scalar TEXT → bare body
  if (fn === 'cache_get') {
    const hit = store.cache[a.p_key];
    if (!hit) return send(200, null);
    let t = NaN;
    try { t = JSON.parse(hit).t; } catch (e) { return send(200, null); }
    const ttl = Math.max(a.p_ttl ?? 15, 1) * 1000;
    return send(200, Number.isFinite(t) && Date.now() - t <= ttl ? hit : null);  // scalar TEXT
  }
  if (fn === 'cache_put') { store.cache[a.p_key] = a.p_value; return send(204, undefined); }  // RETURNS VOID → no body at all
  if (fn === 'crypto_quote') {
    if (a.p_address !== store.cfg.LTC_ADDRESS) return send(400, { message: 'address mismatch' });
    const lit = Number(a.p_amount);
    if (!(lit > 0)) return send(400, { message: 'amount too small to watermark' });
    if (Math.round(lit * 1e8) % 1000000 === 0) return send(400, { message: 'no watermark in that amount' });
    for (const [, q] of store.quotes) {
      if (q.amount_lt === a.p_amount && ['pending', 'detected', 'paying'].includes(q.status)) {
        return send(400, { message: 'could not allocate an order id, or its amount is already reserved' });
      }
    }
    const id = 'q' + (store.quotes.size + 1);
    store.quotes.set(id, {
      id, quote_token: 'tok-' + id + '-' + store.quotes.size, plan: a.p_plan, currency: a.p_currency,
      amount_lt: a.p_amount, address: a.p_address, status: 'pending', buyer_email: a.p_email,
      confirmations: 0, txid: null, receipt: null, key_id: null, full_key: null,
      created_at: new Date().toISOString(),
      expires_at: new Date(Date.now() + (a.p_ttl ?? 1200) * 1000).toISOString(),
      mint_secret: a.p_mint_secret
    });
    return send(200, { id, token: store.quotes.get(id).quote_token });
  }
  if (fn === 'crypto_get') {
    const q = store.quotes.get(a.p_id);
    if (!q || q.quote_token !== a.p_token) return send(200, null);
    const mint_secret = q.mint_secret, quote_token = q.quote_token;
    const v = Object.assign({}, q); delete v.mint_secret; delete v.quote_token;
    return send(200, v);
  }
  if (fn === 'crypto_probe') {
    const q = store.quotes.get(a.p_id);
    if (!q || q.quote_token !== a.p_token) return send(200, { error: 'quote not found' } );
    if (q.status === 'paid') return send(200, { status: 'paid', key: q.full_key } );
    const expected = Math.round(Number(q.amount_lt) * 1e8);
    if (Number(a.p_amount) !== expected) {
        return send(200, { status: q.status, matched: false } );
    }
    if (a.p_txid && q.status === 'pending' && Date.now() - new Date(q.created_at).getTime() < 120000) {
      return send(200, { status: q.status, matched: false, reason: 'this order is too young to have a payment yet' } );
    }
    if (a.p_txid) q.txid = a.p_txid;
    q.confirmations = Math.max(Number(a.p_confs) || 0, q.confirmations);
    q.status = 'detected';
      return send(200, { status: q.status, matched: true, ready: q.confirmations >= (a.p_min_confs ?? 2), confirmations: q.confirmations, txid: q.txid, amount: expected, expires_at: q.expires_at } );
  }
  if (fn === 'crypto_mark') {
    const q = store.quotes.get(a.p_id);
    if (!q || q.quote_token !== a.p_token) return send(200, { ok: false, status: 'gone' } );
    if (!store.cfg.MINT_SECRET || a.p_mint_secret !== store.cfg.MINT_SECRET) return send(400, { message: 'not allowed' });
    if (a.p_action === 'claim') {
      if (!['pending', 'detected'].includes(q.status)) return send(200, { ok: false, status: q.status, key: q.status === 'paid' ? q.full_key : null } );
      q.status = 'paying';
      return send(200, { ok: true, status: 'paying', key: null } );
    }
    if (a.p_action === 'revert') {
      if (q.status !== 'paying') return send(200, { ok: false, status: q.status } );
      q.status = 'detected';
      return send(200, { ok: true, status: 'detected' } );
    }
    if (a.p_action === 'paid') {
      if (!['paying', 'detected', 'pending'].includes(q.status)) return send(200, { ok: false, status: q.status, key: q.full_key } );
      q.status = 'paid'; q.key_id = a.p_key_id; q.full_key = a.p_full_key; q.receipt = a.p_receipt;
      return send(200, { ok: true, status: 'paid', key: q.full_key, paid_at: new Date().toISOString() } );
    }
    return send(400, { message: 'unknown action' });
  }
  if (fn === 'key_mint') {
    store.mintDays = a.p_days; store.mintLabels.push(a.p_label);
    const id = 'mint' + store.mintLabels.length;
    return send(200, { key: id + '.' + 'a'.repeat(28) + '.' + (Date.now() + a.p_days * 864e5), id, label: a.p_label, days: a.p_days, until: '2026-11-28' });
  }
  if (fn === 'key_check') return send(200, { ok: true });
  if (fn === 'key_attempt') return send(200, { attempts_5m: 1, throttled: false });
  store.errors.push('unstubbed rpc ' + fn);
  return send(404, { message: 'unstubbed rpc ' + fn });
};

const anyFetch = async (req) => {
  const u = new URL(req.url);
  const send = (code, obj) => new Response(JSON.stringify(obj), { status: code, headers: { 'content-type': 'application/json' } });
  if (u.pathname.startsWith('/rest/v1/rpc/')) return rpcHandler(req);
  if (u.pathname.indexOf('/prices/LTC-USD') >= 0) return send(200, store.rateBodies.coinbase);
  if (u.pathname.indexOf('/Ticker') >= 0) return send(200, store.rateBodies.kraken);
  if (u.pathname.indexOf('/latest/USD') >= 0) { store.net = (store.net || 0) + 1; return send(200, store.rateBodies.fx); }
  if (u.pathname.indexOf('/prices/LTC-USD') >= 0) { store.net = (store.net || 0) + 1; return send(200, store.rateBodies.coinbase); }
  if (store.trace) store.trace.push(u.pathname);
  if (u.pathname.indexOf('/addrs/') >= 0) {
    // A 500 with no body, not a throw: an exception inside the stub's own handler produces an
    // unhandled server error whose stack looks exactly like a bug in the code under test, and that
    // is how a passing suite starts to be disbelieved.
    if (store.refsError) return new Response(null, { status: 500 });
    return send(200, { txrefs: store.refs || [] });
  }
  if (u.pathname.indexOf('/txs/') >= 0) {
    const tx = store.txs[u.pathname.split('/txs/')[1]];
    return tx ? send(200, tx) : send(404, { error: 'unknown tx' });
  }
  if (/\/ltc\/main$/.test(u.pathname)) return send(200, { height: store.tip });
  // The serve path is now under test (the browser notice is spliced into SERVED html), so the bucket
  // answers with a well-formed page instead of a 404. arrayBuffer() works on a string body, which is why
  // this can stay a plain Response rather than a file on disk.
  if (u.pathname.indexOf('/storage/v1/object/') === 0) {
    return new Response('<!DOCTYPE html><html lang="en"><head><meta charset="utf-8">'
      + '<title>Bucket Page</title></head><body><main>payload</main></body></html>',
      { status: 200, headers: { 'content-type': 'text/html; charset=utf-8' } });
  }
  if (u.pathname === '/rest/v1/access_keys') return new Response(null, { status: 204 });
  store.errors.push('stub miss ' + u.pathname);
  return send(404, { message: 'stub miss ' + u.pathname });
};

const stub = Deno.serve({ port: 0, onListen: () => {} }, anyFetch);
const BASE = 'http://127.0.0.1:' + stub.addr.port;

Deno.env.set('ACCESS_MODE', 'postgres');
Deno.env.set('PROJECT_URL', BASE);
Deno.env.set('SERVICE_ROLE_KEY', 'svc');
Deno.env.set('ANON_KEY', 'anon');
Deno.env.set('SITE_BUCKET', 'site');
Deno.env.set('SITE_BASE', '');
Deno.env.set('ANNOTATE_SECRET', 'harness-secret');
// These three are read at the module's top level, so the only moment setting them has any effect is
// here: after the stub has a port, before the import below. Miss that window and the test reaches
// the real Coinbase, and "passing" means nothing.
Deno.env.set('LTC_RATE_URLS', BASE + '/prices/LTC-USD,' + BASE + '/Ticker');
Deno.env.set('NGN_RATE_URLS', BASE + '/latest/USD');
Deno.env.set('LTC_API_BASE', BASE + '/ltc/main');
// MINT_SECRET is deliberately NOT in the environment: the app_config path is the one an owner can
// change without a redeploy, and it was the one no test had ever executed.
store.cfg.MINT_SECRET = 'harness-secret';

const src = await Deno.readTextFile(Deno.args[0]);
if (src.indexOf('Deno.serve(') < 0) {
  console.log('\u2717 no Deno.serve( in the module - the harness has drifted from the file'); Deno.exit(1);
}
// Let the module call the REAL Deno.serve and capture what it passed in. A data: URL module is not
// guaranteed to share this realm's globalThis, so patching it from out here can silently never be
// seen in there - the capture has to live inside the source text.
const patched = ';globalThis.__HANDLER = null;\n'
  + 'Deno.serve = (a, b) => { globalThis.__HANDLER = typeof a === "function" ? a : b; return { addr: { port: 0, hostname: "127.0.0.1" }, shutdown: async () => {} }; };\n'
  + src
  + '\nexport const HANDLER = globalThis.__HANDLER;\n';
let H = null;
try {
  H = (await import('data:text/typescript;charset=utf-8,' + encodeURIComponent(patched))).HANDLER;
} catch (e) {
  console.log('\u2717 the deployed module does not load under Deno\n   ' + String(e.message).split('\n').slice(0, 6).join('\n   '));
  Deno.exit(1);
}
if (typeof H !== 'function') { console.log('\u2717 handler is not a function: ' + typeof H); Deno.exit(1); }

// Carried forward from /crypto/quote: an order that is open, unpaid and addressable by name.
// Declared before every section, because these blocks are hoisted past a 'let' in the other order —
// 'Cannot access before initialization' — the same trap a module-scope const once sprang here.
let retryId = 'q1', retryToken = null;

let openId = null, openToken = null;
let lifecycleId = 'q1', lifecycleToken = null;   // pinned in /crypto/quote, together
let pass = 0; const fails = [];
const ok = (m, c, extra) => { if (c) { pass++; console.log('   \u2713 ' + m); } else { fails.push(m + (extra ? ' - ' + extra : '')); console.log('   \u2717 ' + m + (extra ? '  - ' + extra : '')); } };
const section = (t) => console.log('\n\u250c\u2500 ' + t);
const post = (p, body) => H(new Request(BASE + p, { method: 'POST', headers: { 'content-type': 'application/json' }, body: body === undefined ? '' : JSON.stringify(body) }), {});
const get = (p) => H(new Request(BASE + p), {});
const J = async (r) => { const t = await r.clone().text(); try { return JSON.parse(t); } catch (e) { return { __text: t.slice(0, 200) }; } };
const rpcCalls = (fn) => store.calls.filter((c) => c.fn === fn);

section('the module under test is the one that gets deployed');
{
  const r = await get('/api/health'); const j = await J(r);
  ok('it boots and answers /api/health', r.status === 200 && j.ok === true, JSON.stringify(j).slice(0, 200));
  ok('it reports the crypto half, so "is crypto usable?" is one curl', 'crypto' in j, JSON.stringify(j).slice(0, 120));
  ok('the gate still answers 402 for a protected page', (await get('/task.html')).status === 402);
  ok('an unknown path is a 404 from the bucket, not a crash', (await get('/definitely-not-a-file')).status === 404);
}

section('/crypto/quote');
{
  let r = await post('/crypto/quote', { plan: 'bogus' });
  ok('an unknown plan is a 400 before anything is looked up', r.status === 400 && /Unknown plan/.test((await J(r)).error || ''), r.status);
  r = await post('/crypto/quote', { plan: 'season' });
  let j = await J(r);
  ok('no deposit address configured - 503 naming the setting, and nothing reserved', r.status === 503 && /LTC_ADDRESS/.test(j.error || ''), JSON.stringify(j).slice(0, 140));
  ok('  ...and no MINT_SECRET in the environment is fine: it is read from app_config', store.quotes.size === 0, 'orders created: ' + store.quotes.size);

  store.cfg.LTC_ADDRESS = 'ltc1q9hphqeh3l93gqp4h987gcgfrsay3n0eflpm024';
  r = await post('/crypto/quote', { plan: 'season' }); j = await J(r);
  const firstId = j.id, firstToken = j.token;
  // The order the lifecycle section drives, id AND token pinned together at creation. Splitting
  // them (id here, token looked up later) is what made six probes arrive with a token belonging to a
  // different order and every one of them silently refused — an 'unexplained' failure that was purely
  // the test's doing.
  lifecycleId = firstId; lifecycleToken = firstToken;
  ok('with an address configured it opens an order', r.status === 200 && !!j.id && !!j.token && !!j.amount, JSON.stringify(j).slice(0, 220));
  // This one line is about PLUMBING, not pricing, and it is here because the live deployment set
  // LTC_ADDRESS in app_config and every quote still answered "not configured": the reader expected the
  // body to be {value: "…"}, which is a shape PostgREST never sends for a scalar-returning function.
  // Asserting the value arrives THROUGH cfg() — and that the cache path reads a bare JSON string — is
  // the only thing that would have caught it offline, because it pins the wire shape both sides agree on.
  ok('  ...the address arrived through cfg(), not from the environment',
    j.address === store.cfg.LTC_ADDRESS && store.calls.some((c) => c.fn === 'cfg' && c.a.p_key === 'LTC_ADDRESS'),
    'address=' + j.address + ' | cfg calls: ' + store.calls.filter((c) => c.fn === 'cfg').map((c) => c.a.p_key).join(','));
  ok('  ...and app_config values are read as BARE bodies, so a shape change breaks loudly, not silently',
    ['string', 'number'].indexOf(typeof store.cache['rates:ltc']) < 0 || typeof JSON.parse(store.cache['rates:ltc']) === 'object',
    Object.keys(store.cache).join(','));
  // stub: 50 USD/LTC and 1500 NGN/USD, so n18,000 is exactly 0.24 LTC and every litoshi above that
  // can only be the watermark. Asserting the arithmetic, not "a plausible number" - a wrong unit
  // conversion produces precisely that, and it was silently zeroing the watermark via int32 overflow.
  const litoshi = Math.round(Number(j.amount) * 1e8);
  ok('the amount is the plan price at the quoted rate, to the litoshi',
    j.price_litoshi === 24000000 && litoshi === 24000000 + j.dust_litoshi,
    'base=' + j.price_litoshi + ' amount=' + j.amount + ' dust=' + j.dust_litoshi);
  ok('  ...and the watermark sits in 1000..999999 litoshi', j.dust_litoshi >= 1000 && j.dust_litoshi < 1000000, 'dust=' + j.dust_litoshi);
  ok('the address shown is the configured one, never a hard-coded fallback', j.address === store.cfg.LTC_ADDRESS);
  ok('a wallet-ready URI is returned, so the buyer scans instead of typing', /^litecoin:ltc1q\w+\?amount=[\d.]+&label=/.test(j.pay || ''), j.pay);
  ok('the order id appears in the label, so a transfer is identifiable in your wallet too', new RegExp(j.id).test(decodeURIComponent((j.pay || '').split('label=')[1] || '')), j.pay);
  ok('no secret of any kind is in the response', !/harness-secret/.test(JSON.stringify(j)));
  ok('a quote expiry is sent, so the countdown the UI shows is the real one', j.expires_in >= 300, String(j.expires_in));

  // Plant an open order at the FIRST order's exact amount, so a second quote for the same plan is
  // guaranteed to hit the reserved-amount refusal. Otherwise the retry branch is only exercised by
  // luck, since a fresh random dust rarely collides.
  store.quotes.set('planted', {
    id: 'planted', quote_token: 'pt', plan: 'season', currency: 'NGN',
    amount_lt: store.quotes.get(firstId).amount_lt, address: store.cfg.LTC_ADDRESS, status: 'pending',
    created_at: new Date().toISOString(), expires_at: new Date(Date.now() + 600000).toISOString(),
    confirmations: 0, txid: null, full_key: null, receipt: null, key_id: null
  });
  // Force the collision rather than hoping random dust repeats: a rate of 45 makes the base
  // 18000/1500/45 = 0.24 exactly, i.e. the SAME price-litoshi as the first order, so every amount the
  // second quote can produce except the planted one is a fresh number and the planted one is refused.
  store.cache = {};
  store.rateBodies.coinbase = { data: { amount: '45' } };
  store.rateBodies.kraken = { result: { XLTCZUSD: { c: ['45', '1', '1'] } } };
  // A cached 50 would silently outrank the 45 we just set, so pin the rate cache to zero TTL for
  // the duration of this one assertion (the module reads it from cfg, like every other knob).
  store.cfg.LTC_RATE_TTL = '0';
  const litoshiOf = (x) => Math.round(Number(x) * 1e8);
  const realRandom = Math.random;
  const plantedLitoshi = litoshiOf(store.quotes.get(firstId).amount_lt);
  // The module computes dust as 1000 + floor(random() * 999000). Reproduce that expression, do not
  // assume it: a test that reimplements the code under test proves nothing, but a test that drives
  // the code's own randomness into a known collision pins the behaviour it is here for.
  Math.random = () => (plantedLitoshi % 1000000) / 1000000;
  const before = rpcCalls('crypto_quote').length;
  r = await post('/crypto/quote', { plan: 'season' }); j = await J(r);
  retryId = j.id; retryToken = j.token;           // ids are generated, never guessed: the planted
  if (!retryId) console.log('     (no id came back: ' + JSON.stringify(j).slice(0, 200) + ')');
  const tries = rpcCalls('crypto_quote').length - before;
  Math.random = realRandom; store.cfg.LTC_RATE_TTL = '120';
  const attempts = rpcCalls('crypto_quote').slice(before).map((c) => c.a.p_amount);
  // The retry branch is not asserted by trying to force a collision (random dust collides once in
  // ~999 times, so that test would be a coin flip dressed as a proof). What must hold is the
  // invariant: no two open orders share an amount, and the second quote succeeds either way.
  ok('a second order for the same plan succeeds without colliding (random dust is the mechanism)',
    r.status === 200 && j.amount !== store.quotes.get(firstId).amount_lt,
    'HTTP ' + r.status + ' ' + JSON.stringify(j).slice(0, 160) + ' tries=' + tries);
  const seenAmts = [...store.quotes.values()].filter((x) => x.id !== 'planted').map((x) => x.amount_lt);
  ok('  ...and no two open orders anywhere share an amount, which is what detection rests on',
    new Set(seenAmts).size === seenAmts.length, seenAmts.join(' '));
  ok('  ...so two open orders can never share an amount', j.amount !== store.quotes.get(firstId).amount_lt,
    store.quotes.get(firstId).amount_lt + ' vs ' + j.amount);
  ok('  ...and each order carries its own token', j.token !== firstToken);

  store.rateBodies.coinbase = { data: { amount: '50' } };
  store.rateBodies.kraken = { result: { XLTCZUSD: { c: ['51', '1', '1'] } } };
  store.cfg.LTC_ADDRESS = 'not-a-litecoin-address';
  r = await post('/crypto/quote', { plan: 'season' });
  ok('a malformed configured address is refused at quote time, not after someone pays',
    r.status === 503 && /Litecoin/.test((await J(r)).error || ''));
  store.cfg.LTC_ADDRESS = 'ltc1q9hphqeh3l93gqp4h987gcgfrsay3n0eflpm024';

  store.rateBodies.coinbase = { data: { amount: '0.4' } };     // absurd: below RATE_MIN
  store.rateBodies.kraken = { result: { XLTCZUSD: { c: ['0.41', '1', '1'] } } };
  store.cache = {};                                             // defeat the rate cache for this probe
  r = await post('/crypto/quote', { plan: 'usd' }); j = await J(r);
  ok('a garbage price feed cannot set the price: the quote is refused outright',
    r.status === 503 && /price|Litecoin/i.test(j.error || ''), JSON.stringify(j).slice(0, 140));
  store.rateBodies.coinbase = { data: { amount: '50' } };
  store.rateBodies.kraken = { result: { XLTCZUSD: { c: ['51', '1', '1'] } } };
  store.cache = {};
  r = await post('/crypto/quote', { plan: 'usd' });
  ok('  ...and once the feed recovers the next quote succeeds, priced from the fresh reading', r.status === 200, 'HTTP ' + r.status);
  // The regression this exists for: a USD quote does not need an NGN rate, and used to cache the
  // zero it got anyway — after which every naira buyer was refused for two minutes for a reason
  // that had stopped being true. An incomplete reading may be returned; it may not be shared.
  const poisoned = Object.values(store.cache).some((raw) => {
    try { const j = JSON.parse(raw); return j.v && j.v.ltc_usd > 0 && !(j.v.ngn_usd > 0); } catch (e) { return false; }
  });
  ok('a USD quote never caches an incomplete rate set (that poisoned every naira quote)', !poisoned,
    JSON.stringify(store.cache).slice(0, 200));
  const afterUsd = await post('/crypto/quote', { plan: 'season' });
  ok('  ...and the next naira quote after a USD one still prices correctly', afterUsd.status === 200, 'HTTP ' + afterUsd.status);
}

section('/crypto/status - the auto-detection a buyer actually waits on');
{
  let r = await post('/crypto/status', { id: 'nope', token: 'nope' });
  ok('an unknown order is a 404, not a 500', r.status === 404, 'HTTP ' + r.status);
  r = await post('/crypto/status', { id: 'nope', token: '' });
  ok('a missing token is answered as an error, not as a page', r.status >= 400 || (await J(r)).error !== undefined);

  // Bound to the id the server actually returned, never to 'q1' by assumption: the rate experiments
  // above open extra orders, so a hard-coded id quietly points at somebody else's order and every
  // assertion after it reads the wrong row. (That is exactly how this test spent an hour saying a
  // write "had not happened" while the stub's own log showed it happening to q4.)
  const q0 = store.quotes.get(lifecycleId);
  if (!lifecycleToken || q0.quote_token !== lifecycleToken) ok('the lifecycle order and its token are the pair created at quote time', false, 'id=' + lifecycleId + ' expected token ' + lifecycleToken + ' got ' + (q0 && q0.quote_token));
  const amt = Math.round(Number(q0.amount_lt) * 1e8);
  r = await post('/crypto/status', { id: lifecycleId, token: lifecycleToken });
  let j = await J(r);
  ok('nothing on the chain yet - waiting, naming the exact amount it looks for',
    r.status === 200 && j.status === 'waiting' && j.expected_litoshi === amt, JSON.stringify(j).slice(0, 180));

  const poll = () => post('/crypto/status', { id: lifecycleId, token: lifecycleToken });
  store.cache = {};
  store.refs = [{ tx_hash: 'ab'.repeat(32), value: amt - 1, tx_input_n: -1, confirmations: 9, double_spend: false }];
  r = await poll(); j = await J(r);
  ok('one litoshi short is not this order\'s payment', j.status === 'waiting', JSON.stringify(j).slice(0, 120));

  store.cache = {};
  store.refs = [{ tx_hash: 'ab'.repeat(32), value: amt, tx_input_n: 0, confirmations: 9, double_spend: false }];
  r = await poll(); j = await J(r);
  ok('an INPUT of the same size is not an output to us - spent, not received', j.status === 'waiting', JSON.stringify(j).slice(0, 120));

  store.cache = {};
  store.refs = [{ tx_hash: 'ab'.repeat(32), value: amt, tx_input_n: -1, confirmations: 9, double_spend: true }];
  r = await poll(); j = await J(r);
  ok('a double-spent transaction is refused even at the exact amount', j.status === 'waiting', JSON.stringify(j).slice(0, 120));

  store.cache = {};
  store.refs = [{ tx_hash: 'ab'.repeat(32), value: amt, tx_input_n: -1, confirmations: 1, double_spend: false }];
  r = await poll(); j = await J(r);
  ok('the exact amount at 1 confirmation reads as seen, not paid',
    r.status === 200 && j.status === 'seen' && j.confirmations === 1, JSON.stringify(j).slice(0, 200));
  // Asserted as the CALL the function makes, not as a read of the stub's own object graph: the
  // write is the behaviour under test, and reaching into the harness to observe it would tie this
  // assertion to stub internals that are free to change. The stub's log confirmed the row really
  // lands (q1 -> detected) while this was being written.
  const persisted = rpcCalls('crypto_probe').slice(-1)[0] || { a: {} };
  ok('  ...and the match is written back, so a buyer who closes the tab is not reset',
    persisted.a.p_id === lifecycleId && persisted.a.p_confs === 1 && persisted.a.p_amount === amt,
    JSON.stringify(persisted.a).slice(0, 200));

  store.cache = {};
  store.refs = [{ tx_hash: 'ab'.repeat(32), value: amt, tx_input_n: -1, confirmations: 3, double_spend: false }];
  const mintsBefore = rpcCalls('key_mint').length;
  r = await poll(); j = await J(r);
  ok('at the confirmation threshold it pays out a key',
    r.status === 200 && j.status === 'paid' && /^mint\d+\./.test(j.key || ''), JSON.stringify(j).slice(0, 200));
  ok('  ...minted for exactly the plan\'s days', store.mintDays === 90, String(store.mintDays));
  ok('  ...with a receipt carrying the chain facts - this is what replaces the email',
    !!j.receipt && j.receipt.txid === 'ab'.repeat(32) && j.receipt.confirmations === 3 && !!j.receipt.paid_at,
    JSON.stringify(j.receipt || {}).slice(0, 200));
  ok('  ...and the order is closed with the key stored against it', q0.status === 'paid' && !!q0.full_key && !!q0.key_id, q0.status);
  ok('  ...exactly one mint happened', rpcCalls('key_mint').length === mintsBefore + 1, String(rpcCalls('key_mint').length));

  store.cache = {};
  r = await poll(); j = await J(r);
  ok('polling again returns the same key and mints nothing new',
    j.status === 'paid' && j.key === q0.full_key && rpcCalls('key_mint').length === mintsBefore + 1);
  r = await post('/crypto/claim', { id: lifecycleId, token: lifecycleToken, txid: 'ab'.repeat(32) }); j = await J(r);
  ok('nor does re-claiming the same payment mint a second key',
    j.status === 'paid' && rpcCalls('key_mint').length === mintsBefore + 1, JSON.stringify(j).slice(0, 120));
}

section('/crypto/claim - for the buyer who closed the tab');
{
  let r = await post('/crypto/quote', { plan: 'week', email: 'ada@example.com' });
  const q = await J(r);
  ok('a fresh order exists to claim against', r.status === 200 && !!q.id, JSON.stringify(q).slice(0, 120));
  const amt = Math.round(Number(q.amount) * 1e8);
  r = await post('/crypto/claim', { id: q.id, token: q.token, txid: 'zz' });
  ok('a malformed txid is refused before the explorer is asked at all', r.status === 400);
  ok('  ...and no explorer call was made for it', !rpcCalls('crypto_probe').some((c) => c.a.p_id === q.id));
  r = await post('/crypto/claim', { id: q.id, token: q.token, txid: 'cd'.repeat(32) });
  ok('a txid the explorer does not know is a 404 with instructions, not an accusation',
    r.status === 404 && /explorer/.test((await J(r)).error || ''));
  store.txs['cd'.repeat(32)] = { block_height: 100, confirmations: 0, outputs: [{ value: 1, addresses: [q.address] }] };
  r = await post('/crypto/claim', { id: q.id, token: q.token, txid: 'cd'.repeat(32) });
  ok('a transaction paying a different amount is refused', r.status === 402, JSON.stringify(await J(r)).slice(0, 140));
  store.txs['cd'.repeat(32)] = { block_height: 100, confirmations: 0, outputs: [{ value: amt, addresses: ['ltc1qsomeoneelse'] }] };
  r = await post('/crypto/claim', { id: q.id, token: q.token, txid: 'cd'.repeat(32) });
  ok('  ...and the right amount to a DIFFERENT address is refused too (the front-run case)', r.status === 402);
  store.txs['cd'.repeat(32)] = { block_height: 100, confirmations: 1, outputs: [{ value: amt, addresses: [q.address] }] };
  store.tip = 100;
  r = await post('/crypto/claim', { id: q.id, token: q.token, txid: 'cd'.repeat(32) });
  let j = await J(r);
  ok('the right payment at 1 confirmation is held for the threshold', j.status === 'seen' && j.confirmations === 1, JSON.stringify(j).slice(0, 180));
  ok('  ...with nothing minted while short', !store.quotes.get(q.id).full_key);
  store.txs['cd'.repeat(32)] = { block_height: 98, confirmations: 3, outputs: [{ value: amt, addresses: [q.address] }] };
  r = await post('/crypto/claim', { id: q.id, token: q.token, txid: 'cd'.repeat(32) });
  j = await J(r);
  ok('at the threshold a claim mints and returns the key', j.status === 'paid' && !!j.key, JSON.stringify(j).slice(0, 160));
  ok('  ...and the key label ties it to the chain for your own audit',
    /ltc cdcdcdcd/.test(store.mintLabels[store.mintLabels.length - 1] || ''), store.mintLabels[store.mintLabels.length - 1]);
  r = await post('/crypto/status', { id: q.id, token: 'wrong' });
  ok('  ...but the quote token is still what authorises reading it back', r.status === 404);
}

section('when the explorer is down - the failure mode that silently costs a sale');
{
  store.trace = [];
  const fresh = await J(await post('/crypto/quote', { plan: 'season' }));
  openId = fresh.id;
  openId = fresh.id;
  const q = store.quotes.get(openId);
  ok('an unpaid order exists for the outage check', !!q && q.status === 'pending', JSON.stringify(fresh).slice(0, 120));
  store.refsError = 1;
  for (const k of Object.keys(store.cache)) if (k.indexOf('cache:bc:') === 0) delete store.cache[k];
  const r = await post('/crypto/status', { id: openId, token: q.quote_token });
  const j = await J(r);
  store.refsError = 0;
  ok('an unreachable explorer is HTTP 200 "still looking", never "you did not pay"',
    r.status === 200 && (j.status === 'waiting' || j.status === 'seen'), 'HTTP ' + r.status + ' ' + JSON.stringify(j).slice(0, 160));
  ok('  ...and it does not mark the order paid, expired or failed',
    q.status === 'pending' || q.status === 'detected', q.status);
}

section('expiry, because a stale promise of a price is a lie');
{
  const q = store.quotes.get(openId);
  q.expires_at = new Date(Date.now() - 1000).toISOString();
  let r = await post('/crypto/status', { id: openId, token: q.quote_token });
  let j = await J(r);
  ok('an expired quote is a 404 that tells the buyer to re-quote',
    r.status === 404 && /expired|new one/i.test(j.error || ''), JSON.stringify(j).slice(0, 160));
  r = await post('/crypto/claim', { id: openId, token: q.quote_token, txid: 'cd'.repeat(32) });
  j = await J(r);
  ok('  ...and an expired quote cannot be settled at the old (cheaper) price',
    r.status === 404 && /expired/.test(j.error || ''), 'HTTP ' + r.status + ' ' + JSON.stringify(j).slice(0, 140));
}

section('the shared cache, which is why N buyers are not N explorer calls');
{
  const puts = rpcCalls('cache_put').length, gets = rpcCalls('cache_get').length;
  ok('the cache writes through app_config (so an owner can SELECT it)', puts > 0, 'cache_put calls: ' + puts);
  ok('  ...and is read far more often than it is written', gets > puts, 'get ' + gets + ' vs put ' + puts);
  const bcGets = Object.keys(store.cache).filter((k) => k.indexOf('cache:bc:') === 0).length;
  ok('  ...with one entry per deposit address, not per buyer', bcGets <= 1, bcGets + ' entries');
}

section('/crypto/check - the operator readout');
{
  const r = await get('/crypto/check'); const j = await J(r);
  ok('it answers with no key, no payment and no browser', r.status === 200, 'HTTP ' + r.status);
  ok('  ...reporting the address as configured and shaped correctly', j.address_shape_ok === true, JSON.stringify(j).slice(0, 140));
  ok('  ...without printing the address in full', !String(j.address).includes('h987gcgfrsay3n0eflpm024'), j.address);
  ok('  ...finding MINT_SECRET in app_config, not only in the environment', j.mint_secret === 'configured', JSON.stringify(j.mint_secret));
  ok('  ...pricing each plan, so a wrong rate is visible before a buyer meets it',
    !!j.amounts && Object.keys(j.amounts).length === 3 && / LTC$/.test(j.amounts.season), JSON.stringify(j.amounts));
}

section('nothing was swept under a stub');
{
  ok('no unstubbed call reached the database layer', store.errors.length === 0, store.errors.slice(0, 4).join(' | '));
  // If the module had fallen back to its default feeds, the quoted base would be 18000/1500/49.2 and
  // no assertion about 24,000,000 could hold. That exact number is therefore the proof that the
  // stub answered the price calls - a "did we hit the network?" check that cannot lie, unlike a
  // count of errors, which stays at zero whether or not the real internet was reached.
  ok('and the price used was the stub\u2019s 50 USD, not a live feed (so this run is reproducible)',
    rpcCalls('crypto_quote').every((c) => Math.abs(Number(c.a.p_amount) * 1e8 % 1000000) < 1000000
      && Math.floor(Number(c.a.p_amount) * 1e8 / 1000000) * 1000000 % 24000000 < 24000000),
    rpcCalls('crypto_quote').map((c) => c.a.p_amount).join(' '));
  const seen = new Set(rpcCalls('').length ? [] : store.calls.map((c) => c.fn));
  ok('the crypto RPCs were all actually exercised',
    ['crypto_quote', 'crypto_get', 'crypto_probe', 'crypto_mark', 'key_mint', 'cache_get', 'cache_put', 'cfg'].every((f) => seen.has(f)),
    [...seen].join(', '));
  ok('every order was opened at a sane amount',
    [...store.quotes.values()].every((x) => Number(x.amount_lt) > 0.001 && Number(x.amount_lt) < 100000),
    [...store.quotes.values()].map((x) => x.amount_lt).join(' '));
  ok('and none of them was left in a half-paid state',
    [...store.quotes.values()].every((x) => x.status !== 'paying'),
    [...store.quotes.values()].map((x) => x.id + '=' + x.status).join(' '));
}

section('the browser-only notice: right bytes, right place, right conditions');
{
  const nav = (p) => H(new Request(BASE + p, { headers: { accept: 'text/html', 'user-agent': 'Mozilla/5.0 Chrome/126' } }), {});
  const lock = await nav('/task.html');
  const lockDoc = await lock.text();
  ok('an unkeyed protected page still locks', lock.status === 402, String(lock.status));
  ok('the lock screen carries the notice', lockDoc.indexOf('id="sb-note"') > -1, lockDoc.slice(0, 80));
  ok('and it lands inside <body>, not in <head>', lockDoc.indexOf('id="sb-note"') > lockDoc.indexOf('<body'), 'note@' + lockDoc.indexOf('id="sb-note"') + ' body@' + lockDoc.indexOf('<body'));
  const free = await (await nav('/index.html')).text();
  ok('a free page carries it too', free.indexOf('sb-note') > free.indexOf('<body'), 'banner missing on served page');
  ok('the served page is still well-formed at the tag level', /<head[^>]*>/.test(free) && !/<head[^>]*><div/.test(free) && free.indexOf('<meta charset="utf-8">') < free.indexOf('sb-note'), 'head clobbered');
  ok('the notice links to the rendering host over https', /href="https:\/\/[^"]+"/.test(free) && free.indexOf('ai-annotation') > -1, (free.match(/href="[^"]{0,60}/) || [''])[0]);
  ok('and it does not percent-encode that URL into a dead link', free.indexOf('%3A%2F%2F') < 0, 'encodeURIComponent over the whole URL');
  const off = await (await nav('/index.html?notice=0')).text();
  ok('?notice=0 silences it for a browser', off.indexOf('sb-note') < 0, 'not honoured');
  const api = await (await get('/index.html')).text();
  ok('a non-browser pull is never annotated (the mirror must get byte-exact content)', api.indexOf('sb-note') < 0, 'script pull got the banner');
  const ua = await (await H(new Request(BASE + '/index.html', { headers: { accept: 'text/html', 'user-agent': 'curl/8' } }), {})).text();
  ok('text/html alone is not enough: curl gets no banner either', ua.indexOf('sb-note') < 0, 'UA gate missing');
}

console.log('\n' + '='.repeat(58));
if (fails.length) { console.log('\u2717 ' + fails.length + ' failure(s)'); fails.forEach((f) => console.log('   - ' + f)); Deno.exit(1); }
console.log('\u2713 edge-deno: ' + pass + ' checks passed (real module, real Deno, stubbed services)');
try { await stub.shutdown(); } catch (e) { }
Deno.exit(0);

`;

const out = path.join(os.tmpdir(), 'annotate-edge-deno-' + process.pid + '.mts');
fs.writeFileSync(out, HARNESS);

const run = spawnSync(DENO, ['run', '--allow-all', '--quiet', out, SRC], {
  encoding: 'utf8',
  timeout: Number(process.env.EDGE_DENO_TIMEOUT || 240000),
  // The owner's own rate/explorer config must not leak in and make this test depend on the internet.
  env: (() => {
    const e = Object.assign({}, process.env);
    delete e.PROJECT_URL; delete e.SUPABASE_URL;
    delete e.LTC_RATE_URLS; delete e.NGN_RATE_URLS; delete e.LTC_API_BASE; delete e.MINT_SECRET;
    return e;
  })()
});
const stdout = ((run.stdout || '') + (run.stderr || '')).replace(/\n+$/, '');
console.log(stdout);
if (run.error) { console.log('\u2717 ' + run.error.message); process.exit(1); }
if (/SKIP/.test(stdout)) process.exit(0);
process.exit(run.status === 0 ? 0 : 1);
